# Database credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: rideshare-data
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: postgres-credentials
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: rideshare/postgres
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: rideshare/postgres
        property: password
    - secretKey: POSTGRES_REPLICATION_USER
      remoteRef:
        key: rideshare/postgres
        property: replication_username
    - secretKey: POSTGRES_REPLICATION_PASSWORD
      remoteRef:
        key: rideshare/postgres
        property: replication_password
---
# Redis credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-credentials
  namespace: rideshare-data
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: redis-credentials
    creationPolicy: Owner
  data:
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: rideshare/redis
        property: password
---
# Application secrets for platform services
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: rideshare-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: rideshare/app
        property: jwt_secret
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: rideshare/app
        property: encryption_key
---
# Payment provider secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: payment-secrets
  namespace: rideshare-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: payment-secrets
    creationPolicy: Owner
  data:
    - secretKey: STRIPE_SECRET_KEY
      remoteRef:
        key: rideshare/payment
        property: stripe_secret_key
    - secretKey: STRIPE_WEBHOOK_SECRET
      remoteRef:
        key: rideshare/payment
        property: stripe_webhook_secret
---
# Notification service secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notification-secrets
  namespace: rideshare-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: notification-secrets
    creationPolicy: Owner
  data:
    - secretKey: TWILIO_ACCOUNT_SID
      remoteRef:
        key: rideshare/notifications
        property: twilio_account_sid
    - secretKey: TWILIO_AUTH_TOKEN
      remoteRef:
        key: rideshare/notifications
        property: twilio_auth_token
    - secretKey: FCM_SERVER_KEY
      remoteRef:
        key: rideshare/notifications
        property: fcm_server_key
